### ISSUE TITLE
Support for searching MultiValueField

### ISSUE THREAD

**Issue by rhblind** [inonit/drf-haystack#1]
HaystackFilter should be able to construct queries like:

    SearchQuerySet().filter(groups__in=[g.id for g in user.groups.all()])

**Comment by rhblind** [comment]
Should also support other features such as faceting

**Comment by elchudi** [comment]
thanks for the library @rhblind

**Comment by rhblind** [comment]
Yeah, this has not really been prioritized.. But would definitely be useful in certain circumstances.

I'll see if it can be done soon!
Glad you like it 😊

**Comment by rhblind** [comment]
This was fixed as a side effect in https://github.com/inonit/drf-haystack/pull/14/files =)
