### ISSUE TITLE
How to get it work with Django-Haystack?

### ISSUE THREAD

**Issue by xuezhaokun** [inonit/drf-haystack#101]
I've already had my Django-Haystack application with SOLR working. I want to build an Django Rest framework API for my application. By doing some research, I found the library drf-haystack. I followed the steps on the Basic Use example on its [documentation][1]

  [1]: https://drf-haystack.readthedocs.io/en/latest/01_intro.html.
But it seems it doesn't work with my current existing Django-Haystack application. I got error about  "A server error occurred. Please contact the administration." Here are some details about my code.
I have a model called Resource:

    class Resource(models.Model):
      title = models.CharField(max_length=100)
      author = models.CharField(max_length=30)

For my Django-Haystack app, I have my index class:

    class ResourceIndex(indexes.SearchIndex, indexes.Indexable):
      text = indexes.CharField(document=True, use_template=True)
      title = indexes.CharField(model_attr="title")
      author = indexes.CharField(model_attr="author")

For my drf-haystack, I have the following serializer and api view class:

    class ResourceSerializer(HaystackSerializer):

      class Meta:
          index_classes = [ResourceIndex]
          fields = [
              "text", "title", "author"
          ]

    class ResourceAPIView(HaystackViewSet):
      index_models = [Resource]

      serializer_class = ResourceSerializer

In my urls.py, I have

    router = routers.DefaultRouter()
    router.register("resource", ResourceAPIView, 
                     base_name="resource-api")

    urlpatterns = patterns("",
      url(r'^', include(router.urls)),
      url(r'^search/$', MyView.as_view(), name='haystack_search'))

BTW, I am using Django-Haystack 2.5.0 with SOLR and drf-haystack 1.6.1

Does anyone have any idea?

**Comment by eayantsquare** [comment]
https://drf-haystack.readthedocs.io/en/latest/01_intro.html there is a warning in the intro that saying basic usage code might not work. I guess it was hard for the developer of this library to actually put an example that does work.

**Comment by rhblind** [comment]
Hi,
The library has been developed using ElasticSearch as the search backend. I'm quite busy these days and don't have much time for some really needed maintenance. I'll try to have a look at it soon-ish™.

**Comment by rhblind** [comment]
Closed due to no answers - please reopen if still having problems.
