### ISSUE TITLE
ViewSet filtering backend doesn't work with rest_framework.filters.OrderingFilter

### ISSUE THREAD

**Issue by rrgrs** [inonit/drf-haystack#102]
When I plug in the rest_framework.filters.OrderingFilter filter backend into my viewset, searches no longer react to any search inputs other than the ordering. My viewset configuration is very simple and works fine with the OrderingFilter usage commented out, so I won't bother posting code unless someone asks.

Is this a known issue with this filter? Is there a better or alternate way to dynamically set the ordering using the REST API?

This is an important feature, so if there's no good answer to this I'd like to act to make sure this gets implemented.

Thanks

**Comment by rhblind** [comment]
Hi,
Can you try to put the `OrderingFilter` as the last filter in the list?
Other than that, I don't seem to have any test cases that uses the OrderingFilter, so frankly I'm not quite sure...
Any contributions to make it work would be appreciated =)

**Comment by rrgrs** [comment]
If anyone's coming across this, it was solved by creating a child class that inherits from both the rest_framework ordering filter and the haystack filter built into the drf-haystack lib like so:

`class HayStackOrderingFilter(OrderingFilter, HaystackFilter):
    pass`

I would do a PR to add this as one of the packaged drf-haystack filters but I haven't written any tests for it yet.

**Comment by rhblind** [comment]
Great, good job!
If you want it merged, please provide tests as well =)
