### ISSUE TITLE
Limiting resultset per model in aggregated HaystackSerializer

### ISSUE THREAD

**Issue by daughterlycare** [inonit/drf-haystack#109]
I'm sorry if this has been posted before, but I am unable to find it.

I am not sure how to limit the amount of results returned per model in a HaystackSerializer.

i.e. Running an aggregate search over 4 models but only returning 5 results per model, resulting in 20 total results.

Any help would be appreciated.

**Comment by rhblind** [comment]
Hi, you can use pagination on your view as you'd normally do with rest framework.

**Comment by rhblind** [comment]
Hi, did you figure this out?

**Comment by daughterlycare** [comment]
Yes I did thank you.

**Comment by rhblind** [comment]
Great!
