### ISSUE TITLE
Could not find serializer for <foo.MymodelIndex object at 0xthings> in mapping

### ISSUE THREAD

**Issue by ursomniac** [inonit/drf-haystack#111]
Nothing in the documentation gives any CLUE why this should happen, or how to fix it.

Is there any better documentation out there?  

Or any code example giving back results from multiple models that works?

**Comment by rhblind** [comment]
Hi, sorry I have no idea where this error comes from.. Can you please share some code and explain what you're doing that cause this error?

**Comment by ursomniac** [comment]
I'm happy to (and I greatly appreciate any help I can get), but I've got another more basic issue (#112) that I'd like to solve first.

**Comment by rhblind** [comment]
Do you still have problems with this, or can I close this issue?

**Comment by ursomniac** [comment]
I still haven't been able to get this to install.   The client is pretty upset and is looking at other ways to get the functionality they need.

**Comment by rhblind** [comment]
What problems are you facing? 
Can you try using the following?

**python libraries**
- `elasticsearch>=2.0.0,<3.0.0`
- `django-haystack>=2.7`
- `drf-haystack>=1.8.1`

**settings.py**
```
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch2_backend.Elasticsearch2SearchEngine'  # <-- Important!
        'URL': os.environ.get('ELASTICSEARCH_URL', 'http://localhost:9200/'),
        'INDEX_NAME': 'my-index',
        'INCLUDE_SPELLING': True,
        'TIMEOUT': 300,
    },
}
```
