### ISSUE TITLE
How to connect the querystring to the search term?

### ISSUE THREAD

**Issue by ursomniac** [inonit/drf-haystack#112]
I've followed the instructions for setting up search on a particular model (Article).
However, when I attempt to run a search with /site-search/?q=elephant, I get all of my articles back (regardless of the search term).   If I force a query through the shell, e.g.:

y= SearchQuerySet().auto_query('elephant')

I get back a perfectly good result set.   So clearly, I'm somehow missing a step that processes the "q" value and sends it to the search engine.  (When I've done this on other sites that aren't using DRF, I don't recall having to do any additional coding to set that up, so I apologize in advance if I'm overlooking something obvious.)

(This site also uses Swagger, and that interface is also not showing a place to insert a search term either - again implying I've overlooked something.   Unfortunately I inherited this codebase, and it's rather "complicated" so the basic setup described in the docs might be just fine and I just have a test case that gets underfoot...)

**Comment by rhblind** [comment]
Hi, it's a bit hard to tell what's wrong without some context, code examples and so on.
The field aliases is set up in the serializer class, like demonstrated [here](http://drf-haystack.readthedocs.io/en/latest/02_autocomplete.html).

**Comment by ursomniac** [comment]
I'm not using autocomplete so I don't see the relevance of your link.    I just want a simple search engine that returns REST.  But none of your examples actually do this; they're all filters on specific fields of models (e.g., "city name").   Am I misunderstanding what this package is for?

**Comment by ursomniac** [comment]
Or to restate the question:   why does

y= SearchQuerySet().auto_query('elephant')

work, but

http://127.0.0.1:8010/?q=elephant

does not using the basic setup in your installation instructions?    AFAICT there's nothing in your code that hooks the variable used for the search term (here, 'q') TO anything.   Instead it appears that your code ONLY sets up field-level filtering (e.g., if you have a PlaceName model you can set up a city filter).

**Comment by rhblind** [comment]
The relevance of the link is that it demonstrates how you set up the mapping of the field alias, ie. the `?q=` part of your query string.
Since you're not sharing any source code for search indices, views or serializers it's hard for me to tell you why your query does not work.

You're not misunderstanding the purpose of the library, but you'll have to apply at least one filter as they are responsible for turning your query string parameters into query parameters for the search engine. If you don't set a filter, it will use the `HaystackFilter` by default which will work good for querying specific fields in the search index.

**Comment by ursomniac** [comment]
OK - I've started over.

Now I don't get a runtime error, but I also do not get any results.  If I do the query in the shell (using Haystack and completely ignoring drf_haystack) I get results.

Here is all the relevant source code:

1)  urls.py:

```
urlpatterns = (
    ...
        url(
        r'^v1/',
        include('myproj.api.urls')
    ),
)
```

2) myproj/api/urls.py:  (necessary because of the large number of apps involved)

```
urlpatterns = (
    ...
    url(
        r'^site-search/',
        include('myproj.search.api_urls')
    )
)
```

3) myproj/search/api_urls: (basically just copied from the drf_haystack docs example, but I'll need to expand this to ~5-7 other models for a global search once I get the "one model" example working at all):

```
from django.conf.urls import patterns, url, include
from rest_framework import routers

from .api_views import ArticleSearchView

router = routers.DefaultRouter()
router.register("article/search", ArticleSearchView, base_name="article-search")


urlpatterns = patterns(
    "",
    url(r"^$", include(router.urls)),
)
```

4) myproj/search/search_indexes.py  (This is under /search and not /article because almost all the rest is 25,000+ lines of inherited legacy code for the site, and I wanted to keep things separate.)

```
from haystack import indexes
from ..article.models import Article

class ArticleSearchIndex(indexes.SearchIndex, indexes.Indexable):
    
    text = indexes.CharField(document=True, use_template=True)
    meta_description = indexes.CharField(model_attr="meta_description")
    meta_title = indexes.CharField(model_attr='meta_title')
    meta_keywords = indexes.CharField(model_attr='meta_keywords')
    headline = indexes.CharField(model_attr='headline')
    deck = indexes.CharField(model_attr='deck')
    
    
    def get_model(self):
        return Article
        
    def index_queryset(self, using=None):
        return self.get_model().objects.filter(public=True)
```

Running `manage.py rebuild_index` does appear to work properly.

5) myproj/search/serializers.py: (separate from /article/serializers.py because there are already other serializers associated with this model):

```
from drf_haystack.serializers import HaystackSerializer
from .search_indexes import ArticleSearchIndex

class ArticleSearchSerializer(HaystackSerializer):
    
    class Meta:
        index_classes = [ArticleSearchIndex,]
        fields = ['text', 'headline', 'deck']
```

6) myproj/search/api_views.py:

```
from drf_haystack.viewsets import HaystackViewSet
from ..article.models import Article
from .serializers import ArticleSearchSerializer

class ArticleSearchView(HaystackViewSet):
    index_models = [Article,]
    serializer_class = ArticleSearchSerializer
```

7) Test from shell:

```
% python manage.py shell
>>> from haystack.query import SearchQuerySet
>>> sqs = SearchQuerySet().all()
>>> sqs.count() 
155
>>> sqs = SearchQuerySet().filter(content='vase')
>>> sqs.count()
2
```

8) Test from site:

```
http://localhost:8010/v1/site-search/?q=vase

GET /v1/site-search/?q=vase
HTTP 200 OK
Content-Type: application/json
Vary: Accept
Allow: GET, HEAD, OPTIONS

{}
```

So - what have I missed in the documentation?

**Comment by rhblind** [comment]
It seems to me like you're trying to query by passing the value through a `?q=` query parameter, but there's no field in your `ArticleSearchIndex` class which matches the `q` parameter. What happens if you try `?text=vase` for example?

In the link I pasted earlier, there's an entry like
```python
        field_aliases = {
            "q": "autocomplete"
        }
```
with a comment above (this should be in your `ArticleSearchSerializer.Meta` class. You can put this attribute on the serializer class in order to alias a query parameter to a field which exists in your search index class. In the example the `q` value is serialized to a field called `autocomplete` which is an `EdgeNgram` field, but this can be whatever field you like. If you want to search the `text` field in your search index class replace "autocomplete" with "text" and you should be good to go.

**Comment by ursomniac** [comment]
I tried text= and other fields with the same results.

**Comment by ursomniac** [comment]
```
        field_aliases = {
            'q': 'text',
        }
```

with  `http://localhost:8010/v1/site-search/?q=vase`  also returns empty results.

**Comment by rhblind** [comment]
Hm, that's weird.
What search engine and version are you running?

**Comment by ursomniac** [comment]
I'm using Whoosh 2.7.4 --- but that's really only for testing.   Given the nature of the project, I expect we'll need to move over to Elasticsearch.
 
I picked Whoosh for the initial tests because I had just used it on another project (without DRF) and ran into no problems there.

**Comment by ursomniac** [comment]
Ok - after a LOT of work, I've changed over from Whoosh to ElasticSearch V2.x.

I GET EXACTLY the SAME behavior as before.   The model IS indexed, I can pull results from the shell just find, but drf_haystack ALWAYS returns NOTHING WHATSOEVER.

Can you point me to any working installation of this software so that I can compare that site's back-end code to mine?

**Comment by rhblind** [comment]
Can you try to run Elasticsearch v1.x branch? Support for v2 is not yet complete, I'm afraid.

**Comment by ursomniac** [comment]
Will do.

**Comment by rhblind** [comment]
Any updated on this? Got it working?

**Comment by ursomniac** [comment]
No I hit a wall trying to install ES1, with something requiring a version of DRF higher than what the roj CT’s code requires...  waiting for local support to get me past that part.

Bob

**Comment by rhblind** [comment]
Did you ever manage to get this working?
Just released `v1.7.1rc2` which supports ES 2.x, feel free to try it out and see if it works any better.

Closing this, please reopen if still having issues.

**Comment by ursomniac** [comment]
Perfect timing!  I’ll try it again soon.

**Comment by rhblind** [comment]
Good to hear!
