### ISSUE TITLE
Error on DecimalField serialization

### ISSUE THREAD

**Issue by vied12** [inonit/drf-haystack#116]
Hello,

When I try to serialize objects with some `DecimalField`, I have an error like

```
missing 2 required positional arguments: 'max_digits' and 'decimal_places'
```

When I dig into the source code, I don't know if this is because of my configuration but this condition is never `True`

https://github.com/inonit/drf-haystack/blob/186328a99167c4b2204abe1dd1f907b597db0316/drf_haystack/serializers.py#L131-L133

What about something like:

```python
if field.model_attr in [d.name for d in model._meta.get_fields()]:
            model_field = model._meta.get_field(field.model_attr)
            kwargs = get_field_kwargs(field.model_attr, model_field)
```

What do you think ?

**Comment by vied12** [comment]
Btw this fix allows me to get my decimals, but there are returned as string

**Comment by rhblind** [comment]
Hello, I'm very sorry I haven't answered before. I'm not currently working on a project which uses Haystack nor drf-haystack so my time working on this is very limited these days.

Could you please paste your traceback and maybe some code examples for the serializers and models you're having problems with?

**Comment by rhblind** [comment]
Fixed in develop branch
