### ISSUE TITLE
class Meta has no attribute 'field_aliases'

### ISSUE THREAD

**Issue by Mr-win7** [inonit/drf-haystack#119]
```
class TeacherSerializer(serializers.ModelSerializer):
    class Meta:
        model = Teacher
        fields = '__all__'

class TeacherSearchSerializer(HighlighterMixin, HaystackSerializerMixin, TeacherSerializer):
    highlighter_css_class = "highlighted-class"
    highlighter_html_tag = "em"
    class Meta(TeacherSerializer.Meta):
        search_fields = ['id', 'name', 'school', 'text']

class Teacher(models.Model):

    name = models.CharField(max_length=255, blank=True)
    school = models.CharField(max_length=255, blank=True)
    title = models.CharField(max_length=255, blank=True)
    telephone = models.CharField(max_length=255, blank=True)
    email = models.CharField(max_length=255, blank=True)
    office = models.CharField(max_length=255, blank=True)
    initial = models.CharField(max_length=1, blank=True)
```

```
Request Method: | GET
-- | --
1.11
AttributeError
class Meta has no attribute 'field_aliases'
/usr/local/lib/python2.7/site-packages/drf_haystack/query.py in build_query, line 116
/usr/local/bin/uwsgi
2.7.13
['.',  '',  '/usr/local/lib/python27.zip',  '/usr/local/lib/python2.7',  '/usr/local/lib/python2.7/plat-linux2',  '/usr/local/lib/python2.7/lib-tk',  '/usr/local/lib/python2.7/lib-old',  '/usr/local/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/site-packages']
```

I tried to read the code and I found that there is no such attribute in HaystackSerializerMixin but HaystackSerializer?

**Comment by rhblind** [comment]
Hm, that's weird. It is set [here](https://github.com/inonit/drf-haystack/blob/master/drf_haystack/serializers.py#L45). But why do you inherit from a `ModelSerializer`? Can't guarantee it will work...

**Comment by rhblind** [comment]
Closing due to no reply

**Comment by Mr-win7** [comment]
sorry, I have nearly forgotten this question. But I just wrote this as the docs "Reusing Model serializers" do. Now I found a solution, just write it like this:
`class TeacherSerializer(serializers.ModelSerializer):
    class Meta:
        model = Teacher
        fields = '__all__'

class TeacherSearchSerializer(HaystackSerializerMixin, TeacherSerializer):
    class Meta(TeacherSerializer.Meta):
        fields = ['id', 'name', 'school']

class MainTeacherSearchSerializer(HighlighterMixin, HaystackSerializer):
    highlighter_css_class = "highlighted-class"
    highlighter_html_tag = "em"
    class Meta:
        serializers = {
            TeacherIndex: TeacherSearchSerializer,
        }
`

But it seems too ugly. Could you teach me how to improve it?
