### ISSUE TITLE
2.0x  Support

### ISSUE THREAD

**Issue by rathish** [inonit/drf-haystack#120]
Hi , now Django-Haystack support 2.0x can publish release with 2.0x ?

**Comment by rhblind** [comment]
Thanks for the heads up! I’ll try to make it happen during the weekend!

**Comment by rhblind** [comment]
Fixed in [v1.8.0](http://drf-haystack.readthedocs.io/en/latest/#v1-8-0).

**Comment by rhblind** [comment]
Whoa, sorry this is not fixed yet. Got some issues in my test scripts which caused them to always run with ES1.x. Gotta pull the package again, sorry.

**Comment by rhblind** [comment]
@cho-is I'll probably push it within an hour or so

**Comment by rhblind** [comment]
Pushed v1.8.1 to PyPI

**Comment by rathish** [comment]
Excellent, thanks.

**Comment by cho-is** [comment]
much appreciated
