### ISSUE TITLE
Push 1.8.0 to PyPI

### ISSUE THREAD

**Issue by decibyte** [inonit/drf-haystack#121]
According the [releases page](https://github.com/inonit/drf-haystack/releases), there's a version 1.8.0. But the most recent available from PyPI is 1.7.1rc2. Please push 1.8.0 to PyPI :)

**Comment by rhblind** [comment]
Yes, unfortunately there was some issues with the test suite for 1.8.0 and I was unsure if it was working at all. It seems like it is fixed now, so I'll push a new release once all tests are green (hopefully within an hour).

**Comment by rhblind** [comment]
Pushed v1.8.1 to PyPI
