### ISSUE TITLE
_get_count function has been removed

### ISSUE THREAD

**Issue by delronkung** [inonit/drf-haystack#127]
REST framework v3.8.2 removed `_get_count` function in `rest_framewok.pagination`, but in drf_haystack.serializers.py it is still using.
`from rest_framework.pagination import _get_count`

**Comment by rhblind** [comment]
Thanks for heads up!

**Comment by rhblind** [comment]
Hey, this has been fixed in https://github.com/inonit/drf-haystack/pull/124
