### ISSUE TITLE
New release for Django 2.2 support

### ISSUE THREAD

**Issue by ddaan** [inonit/drf-haystack#138]
I see that the master branch already supports 2.2, but it's not officially released yet. Is there a schedule to do a release to make drf-haystack available for django 2.2 ? 

If there is anything I can do to help with let me know.

**Comment by rhblind** [comment]
Hey, sorry for the delay. I'll see if I can make a release soon-ish!

**Comment by rhblind** [comment]
Just released v1.8.5 now.
Includes support for Django2.2 as well as rest-framework 3.9.x

**Comment by ddaan** [comment]
thank you so much!
