### ISSUE TITLE
'fields' attribute is always required/'exclude' attribute doesn't work

### ISSUE THREAD

**Issue by jannon** [inonit/drf-haystack#16]
Correct me if I'm wrong, but using the `fields` attribute `HaystackSerializer` subclasses should be optional, correct?  That is, if I had an index like so:
```python
class MyIndex(indexes.SearchIndex):
    text = indexes.CharField(document=True, use_template=True)
    field1 = indexes.CharField(model_attr='field1')
    field2 = indexes.BooleanField(model_attr='field2')
    field3 = indexes.BooleanField(model_attr='field3')

    def get_model(self):
        return MyModel
```

I should be able to create the following serializers that would be equivalent:

```python
class MySearchResultSerializer(HaystackSerializer):
    class Meta:
        index_classes = [MyIndex]

        fields = [
            "text", "field1", "field3"
        ]
```

```python
class MySearchResultSerializer(HaystackSerializer):
    class Meta:
        index_classes = [MyIndex]

        exclude = [
            "field2"
        ]
```

If that is true, I believe there is a problem in [serializers.py:117] (https://github.com/inonit/drf-haystack/blob/master/drf_haystack/serializers.py#L117):
```python
    if field_name not in fields or field_name in exclude or field_name in ignore_fields:
        continue
```

In the case of the second serializer, I would expect that the `text`, `field1`, and `field3` fields were still included.  However, they will not be because they will not be found in `fields` (which is `[]` in this case) and the loop will skip.

I will fix it because I have that and some other changes to better support multiple indexes coming, but I just wanted to make sure that I wasn't missing something.

**Comment by rhblind** [comment]
Hi,
Yes that sounds reasonable =)
Looking forward to your "better support multiple indexes" patch, because I'm not too happy with the current implementation.

Thanks alot!
