### ISSUE TITLE
Apply filter to search results

### ISSUE THREAD

**Issue by igorpejic** [inonit/drf-haystack#25]
Is it possible to apply a filter on the results of the search specific for each request?
I would need something like this:
```python
class ApplesView(ListModelMixin, HaystackGenericAPIView):
    index_models = [Apple]
    serializer_class = AppleSearchSerializer

    def get(self, request, *args, **kwargs):
        queryset=self.list(request, *args, **kwargs).filter(eater=request.user)
        return self.list(request, *args, **kwargs)
```
In this way I would display only the results which concern the creator of the request.

Thank you for the great project.

**Comment by rhblind** [comment]
Hi,
Absolutely! But keep in mind that the QuerySet is a `SearchQuerySet` not a regular one, so you need to have the field you want to filter on in the index.

So you are almost there in the example provided, but you should make sure that the `eater` field in the index is holding the user `id` (We can't index python models). Then make the filter like this:

``` python
queryset=self.list(request, *args, **kwargs).filter(eater=request.user.pk)
```

and you should be good to go!

**Comment by igorpejic** [comment]
@rhblind Thank you for your help, but maybe I am doing something wrong. 
I can't do what you suggested because
 ```python
 self.list(request, *args, **kwargs)
``` 
is a rest framework response of type: `<class 'rest_framework.response.Response'>` not a `SearchQuerySet`.

**Comment by rhblind** [comment]
Ah, right =)
In that case I'd suggest to sublcass from the `HaystackViewSet` where you can override ie. the `filter_queryset()` method.

Something like this should do it:

``` python
class AppleViewSet(HaystackGenericAPIView):
    
    # See http://drf-haystack.readthedocs.org/en/latest/basic_usage.html#views-py for how to set up the HaystackViewSet
    
    def filter_queryset(self):
        queryset = super(AppleViewSet, self).filter_queryset()
        return queryset.filter(eater=self.request.user.pk)
```

**Comment by igorpejic** [comment]
Ok, thank you. I modified your code and the final solution would be this code:

```python
class AppleViewSet(HaystackViewSet):

    # See http://drf-haystack.readthedocs.org/en/latest/basic_usage.html#views-py for how to set up the HaystackViewSet

    def filter_queryset(self, *args, **kwargs):
        queryset = super(AppleViewSet, self).filter_queryset(self.get_queryset())
        return queryset.filter(eater=self.request.user.pk)
```

**Comment by rhblind** [comment]
Yeah, sorry about the typo there. 
That was what I meant :)
