### ISSUE TITLE
Missing Dependency elasticsearch

### ISSUE THREAD

**Issue by buluba89** [inonit/drf-haystack#3]
I am using solr as search backend but when i import HaystackViewSet it raises exception:
>haystack.exceptions.MissingDependency: The 'elasticsearch' backend requires the installation of 'elasticsearch'. Please refer to the documentation.

Installing elasticsearch from pip fixes the problem, but why install an extra dependency that i dont need

Thanks a lot for this great library

**Comment by rhblind** [comment]
Oh, that's not good! I'll make a fix =)

Glad you like it!
