### ISSUE TITLE
ignore_fields and exclude

### ISSUE THREAD

**Issue by decibyte** [inonit/drf-haystack#30]
I'm new to both haystack and and drf-haystack, so pardon me if I'm all wrong because my brain is fried after a long day.

I'm following the examples from the [docs about `ignore_fields`](https://drf-haystack.readthedocs.org/en/latest/advanced_usage.html#drf_haystack.filters.HaystackAutocompleteFilter). But I can't get it to work as expected. I'm basically doing the same as in the example, but fields in `ignore_fields` are still serialized and transfered to the client.

While looking at [the source](https://github.com/inonit/drf-haystack/blob/master/drf_haystack/serializers.py#L139-L144), I think I may have a guess why it is so:

As I understand the logic there, `ignore_fields` is only checked if `exclude` evaluates to `True`. I don't have an `exclude` (and neither does the example in the docs), thus my `ignore_fields` is, alas, ignored.

Do you agree this is what is happening? I'd happily provide a PR for this if you like, but I'd like you to confirm this bug before I do the work. As this is probably a quick fix, you may also want to just do it yourself. Anyway, let me know!

PS: [The old logic](https://github.com/inonit/drf-haystack/commit/006d33838af8ab21592b57e71a29f5d32229bde7#diff-81587f7e1acc0b2424a4e1b2fed346f7L117) seems to make more sense to me.

**Comment by rhblind** [comment]
Hi,
Thanks for reporting!
This seems to have slipped in when we introduced support for multiple serializers. Also, it seems like we're missing unit tests for this, since it hasn't been catched before.

I'd be happy to accept a pull request. `ignore_fields` should work either way.

=)

**Comment by decibyte** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 11/06/2015 04:01 PM, Rolf Håvard Blindheim wrote:

> This seems to have slipped in when we introduced support for
> multiple serializers.

Yeah. Even the comment in the code mentions that it's complicated. It
seems whoever wrote the new check was aware this probably was messed up
:)

Also, it seems like we're missing unit tests for this, since it hasn't
been catched before.

Right. I noticed that afterwards.

> I'd be happy to accept a pull request. `ignore_fields` should work
> either way.

I will give it a shot, including tests, but probably not before next wee
k.

- -- 

Mikkel
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJWPMMSAAoJECYcJXx0qnZLWZEH/3F4Ny19qWAfJ/X0OjKgEG1k
kXkn6UOA1RSsnqgJfGU5+MZ+zxLHOB308iiYciAPsqWE8HPNumxYBwY67XFQHg5T
fN9T75P/+4b8l1Plje2Z2cPA3Cc5FkDiu6c6QJKRnCiMjAWy443LO9LsLyPRTv4d
JlXM9tXoeY9/AuIc7DP78ks2aiqdI7r6AAQ2Bv9NMpIu8K78PX0DPZmB7ntC0D2R
LKQak3WF6mIAjmcqLba6EUWbPTtmiXkyP6XCV/zjpUewqza2PLEapEwQWSgQ8BKw
yT24ML9XcsDCUBs5UjV577DJLOmwZrsl5ExPvyogQB/1xMXjphoeQXhLJcPVebQ=
=MbSI
-----END PGP SIGNATURE-----

**Comment by rhblind** [comment]
Great, thanks =)

**Comment by decibyte** [comment]
I'm giving this a try today, but I have some problems running the existing tests. Can you give me quick step-by-step guide to get them to run (and succeed)?

**Comment by rhblind** [comment]
Hi,
Just run

    $ python setup.py test

If you want to run the tox tests, you need to make sure you have installed the Python version for the tox environment you want to run.
For example, if you want to test Python 2.7 with Django 1.7, you'd have to install Python 2.7 on your computer and run.

    $ tox -e py27-django1.7

Take a look in the `tox.ini` file for what environments that's defined.

**Comment by rhblind** [comment]
Yeah, and also you'd have to install elasticsearch and `libgeos` if you want to test the geo spatial filters.

**Comment by decibyte** [comment]
Okay, that's also what I do (`python setup.py test`). But I get a lot of errors like this one:

`NotFoundError: TransportError(404, u'{"found":false,"_index":"drf-haystack-test","_type":"modelresult","_id":"_query","_version":28,"_shards":{"total":2,"successful":1,"failed":0}}')
ok`

And my result it:

```
Ran 73 tests in 106.792s

FAILED (SKIP=3, errors=3, failures=10)
```

Is there some test data to load into the search index before running the tests?

**Comment by rhblind** [comment]
Hm, weird.
No, the test suite should load all the data it needs in the `setUp` methods in the `TestCase`.
What version of Elasticsearch are you running?

I don't think we're compatible with the 2.x branch yet...

Maybe try to delete the `drf-haystack-test` index manually will help?

**Comment by decibyte** [comment]
Aha! I am running 2.0.0. Let me try with an older version. Thanks!

**Comment by rhblind** [comment]
Yeah, try the 1.9 branch.
Got an open Issue on supporting 2.x

**Comment by decibyte** [comment]
Much better. Thanks again.

**Comment by rhblind** [comment]
Great, np =)

**Comment by decibyte** [comment]
So, there you go, in #32.

**Comment by rhblind** [comment]
Great thanks =)

**Comment by rhblind** [comment]
Fixed by merging #32

**Comment by decibyte** [comment]
You're welcome! Will you also push an update to PyPI?

**Comment by rhblind** [comment]
Yes, I'll try to push it tomorrow.

**Comment by decibyte** [comment]
*bump*

**Comment by rhblind** [comment]
Yeah, sorry I've been a bit busy lately...
I'll do it now =)

**Comment by felix-d** [comment]
+ 1 for this! ignore not working for me with a simple use case
```python
class ShopperSearchSerializer(HaystackSerializer):
    pk = serializers.IntegerField()
    is_followed = serializers.SerializerMethodField()
    profile_picture_tb = serializers.URLField(source='object.profile_picture_tb')

    class Meta:
        index_classes = [ShopperIndex]
        fields = ('text', 'pk', 'name', 'is_followed', 'profile_picture_tb', )
        ignore_fields = ['text']
        field_aliases = {
            "q": "text"
        }
```

**Comment by rhblind** [comment]
Just uploaded to pypi!

**Comment by decibyte** [comment]
@rhblind Thanks a lot!

**Comment by felix-d** [comment]
@rhblind Thanks!!!
