### ISSUE TITLE
The HaystackViewSet does not use the default permission scheme

### ISSUE THREAD

**Issue by BzSpi** [inonit/drf-haystack#37]
The HaystackViewSet overrides the permission_classes variable so that the permission mechanism defined in the settings is bypassed.
HaystackViewSet should not override the permissions globally defined.

**Comment by rhblind** [comment]
Agreed.
It should use whatever specified in the settings, and fallback to the default `AllowAny` permission class.

Pull requests are most welcome ;)

**Comment by BzSpi** [comment]
ok, I'll do that.

**Comment by rhblind** [comment]
Yes, there was a reason once.
We experienced crashes when setting global permission classes, and the viewset did not have it. The quick-fix was to just set a default `AllowAny`, but obviously not the best way to do it.

See [v1.5 changelog](http://drf-haystack.readthedocs.org/en/latest/index.html#v1-5-0) and #15

**Comment by BzSpi** [comment]
I've made a pull request #38 that fixes suppress permission override.

**Comment by rhblind** [comment]
Thank you, I'll have a look at it during the weekend =)
