### ISSUE TITLE
BooleanField always returns true

### ISSUE THREAD

**Issue by naveenkumarg** [inonit/drf-haystack#39]
**search_indexes.py:**
```
class DatasetIndex(indexes.SearchIndex, indexes.Indexable):
    highlight = indexes.BooleanField(indexed=False, model_attr='highlight')
    bool_test = indexes.BooleanField(indexed=False)

def prepare_bool_test(self, obj):
        return False
```

**JSON Response:**
```
{
    "bool_test": true,
    "highlight": true,
}
```

I am trying to serialize boolean value from HayStack Search result. It works fine for other fields except the boolean fields. The boolean fields are always returned as true.

**Comment by rhblind** [comment]
Hi,
I am unable to reproduce this. Can you give some more details?

**Comment by naveenkumarg** [comment]
Hi,

Thanks for your response. Sorry, this issue is related to Haystack and Whoosh (https://github.com/django-haystack/django-haystack/issues/801).

**Comment by rhblind** [comment]
Alright, no problem!
