### ISSUE TITLE
Implement `filter_or` support

### ISSUE THREAD

**Issue by Kelvin-Chu** [inonit/drf-haystack#42]
Howdy,

Thanks for making this library, made things a lot easier for me.  I went through the docs and couldn't find a way to use filter_or from haystack.

For example, I have a date field called date and a boolean field called repeat.  I would like to make a search where the date field matches a specific date OR repeat is true.

I tried "search/?date=2016-03-02;repeat_daily=true" but that seems to be doing an AND filter instead.

Any suggestions?

Cheers,
Kelvin

**Comment by Kelvin-Chu** [comment]
I went over your code and if I understood it correctly, it seems like you implemented the exclude filter but not filter_or.

I resolved my problem by overriding the filter_querset function in my view and appending the result with a second queryset that searches for repeat_daily=true.  However... this is obviously making two passes to the backend so if someone has a better solution, let me know!

**Comment by rhblind** [comment]
Hi,
Glad you find it useful!

You are probably right, I wasn't aware there even was a `filter_or` so I wouldn't be surprised if it's not supported =)
We should definitely support that as well!

Thanks for the report.

**Comment by rhblind** [comment]
Hi,
Sorry for the delay. As far as I can read out from the Haystack docs, `filter_or` is just used for `OR'ing` (woah, big surprise) multiple terms together. We're supporting this behaviour by using either one of:

    /api/search/?lastname=watson&lastname=holmes
    /api/search/?lastname=watson,holmes

The default behaviour of the `HaystackFilter` is to `OR` between terms on the same parameter, so you can either specify the field name you want to search on multiple times, or you can separate the query terms by setting a `lookup_sep` attribute on your view (defaults to comma).

**Comment by rhblind** [comment]
After v1.6 is released you can subclass the `HaystackFilter` backend and change the `HaystackFilter.bool_operator` attribute in order to change default behaviour for that filter to use `operator.or_` instead of `operator.and_` as the default boolean function for query parameters.
