### ISSUE TITLE
Documentation doesn't have an api reference

### ISSUE THREAD

**Issue by karimamer** [inonit/drf-haystack#48]
I think it will be easier to use this library if there was an api reference like how DRF has.
thank you for this library it made my life easier

**Comment by rhblind** [comment]
Hi, thanks!
Yeah, absolutely that's a good idea!

**Comment by karimamer** [comment]
i would love something like this http://www.cdrf.co/3.1/rest_framework.viewsets/ModelViewSet.html
should i close this issue

**Comment by rhblind** [comment]
Just leave it open.
Feel free to submit a PR if you wish =)

**Comment by karimamer** [comment]
I will try to get it done this week end

**Comment by rhblind** [comment]
Not pretty, but here's something...

http://drf-haystack.readthedocs.io/en/latest/apidoc/modules.html

**Comment by karimamer** [comment]
thank you 👍  sorry i never got to it

**Comment by rhblind** [comment]
Np ;)
