### ISSUE TITLE
geopy dependency

### ISSUE THREAD

**Issue by bufke** [inonit/drf-haystack#5]
I do see geopy as a requirement, but it isn't ideal if someone wants to use this without it.

Trying to run drf-haystack makes references to gis.geos which in many cases is not desired. Many Linux distributions do not come with libgeos so a gis error is generated when the user may not be doing anything with gis. Perhaps there is a way this could be imported without requiring libgeos. If not this should be stated in docs.

```
File "/usr/local/lib/python3.4/site-packages/drf_haystack/filters.py", line 12, in <module>
from haystack.utils.geo import D, Point
File "/usr/local/lib/python3.4/site-packages/haystack/utils/geo.py", line 2, in <module>
   from django.contrib.gis.geos import Point
ImportError: cannot import name 'Point'
```

**Comment by rhblind** [comment]
Hi, thanks for the issue report.
I really haven't considered this, but as you say, some users might want need the spatial search features.

I'll see what I can do, but I'm a bit busy at work these days, so I really can't make any promises =)

**Comment by applecat** [comment]
I have the same problem with "import name Point" from django.contrib.gis.geos.
It will be great if we can use drf-haystack without massive GeoDjango dependency.
Thanx %)

**Comment by rhblind** [comment]
Fixed.
Uploaded v1.3 to pypi.
