### ISSUE TITLE
How to use the `__in` field lookup?

### ISSUE THREAD

**Issue by decibyte** [inonit/drf-haystack#51]
I'm trying to use the `__in` field lookup, but I can't figure out the syntax for the value of it.

An example: If I query `/path/to/search/?color=blue`, I get all blue objects. If I query `/path/to/search/?color=red`, I get all red objects. But how do I get objects that are either blue or red?

I tried `/path/to/search/?color__in=x`, where x is:

 * `red,blue`
 * `red|blue`
 * `[red,blue]`
 * `['red','blue']`

But without any luck so far. Can anyone help me?

**Comment by rhblind** [comment]
Hi,
The `__in` field lookup expects some kind of iterable (like the `MultiValueField`)  to look in, and I think it should work ok ([at least I did close the issue at some point](https://github.com/inonit/drf-haystack/issues/1)), but if you're trying to use it on ie. a `CharField`, it will create a query like this:
```
query: http://localhost:8000/search1/?lastname__in=hickman,hood
produces: (lastname:("h" OR "i" OR "c" OR "k" OR "m" OR "a" OR "n") OR lastname:("h" OR "o" OR "o" OR "d"))
```

This is probably not what you want, so if you have an index with a `CharField` you should be able to query either one of them (using the regular `HaystackFilter`) like this:
```
query: http://localhost:8000/search1/?lastname__in=hickman,hood
produces: (lastname:(hickman) OR lastname:(hood))
```

Hope this clears things up a bit!

**Comment by decibyte** [comment]
@rhblind, thanks a lot!

There's just one thing I'm still not sure I understand: What's the point of the `HaystackAutocompleteFilter` compared to the regular `HaystackFilter`? It seems the regular filter does the same searching within `(Edge)NgramField`s. At least when following the examples from the docs, and then trying to replace one filter with the other.

**Comment by rhblind** [comment]
The main difference is that the regular `HaystackFilter` performs a binary `OR` comparison between terms of the same parameter, while the `HaystackAutocompleteFilter` performs an `AND`.
