### ISSUE TITLE
drf-haystack with django-autocomplete-light

### ISSUE THREAD

**Issue by geekashu** [inonit/drf-haystack#52]
Hi,

I am trying to implement django-haystack and drf-haystack in such a way that it work with django-autocomplete-light. I have this code..
````
from drf_haystack.serializers import HaystackSerializer
from rest_framework.mixins import ListModelMixin
from drf_haystack.generics import HaystackGenericAPIView
from drf_haystack.filters import HaystackAutocompleteFilter

from users.search_indexes import LocationIndex
from users.models import Location

class AutocompleteSerializer(HaystackSerializer):
    class Meta:
        index_classes = [LocationIndex]
        fields = ["text", "state", "autocomplete_city"]
        ignore_fields = ["text", "state"]

class LocationAutocompleteView(ListModelMixin, HaystackGenericAPIView):
    index_models = [Location]
    serializer_class = AutocompleteSerializer
    filter_backends = [HaystackAutocompleteFilter]

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)
````

I want the output from the view above in the format like this..
```
{

    "pagination": 

{

    "more": true

},
"results": 
[

{

    "text": "Bokaro Steel City",
    "id": "94"

},
{

    "text": "Rajahmundry",
    "id": "95"

},
{

    "text": "Ballari",
    "id": "96"

},
{

    "text": "Latur",
    "id": "99"

},
{

    "text": "Bilaspur",
    "id": "109"

},
{

    "text": "Tumkur",
    "id": "116"

}
]
}
```

My code above returns all the results in this format... also results are not being paginated..
```
[
    {
        "autocomplete_city": "Hyderabad"
    },
    {
        "autocomplete_city": "Chennai"
    },
    {
        "autocomplete_city": "Pune"
    },
    {
        "autocomplete_city": "Surat"
    },
    {
        "autocomplete_city": "Nagpur"
    },
    {
        "autocomplete_city": "Patna"
    },
```

Any help is highly appreciated. 
Regards

**Comment by rhblind** [comment]
Hi,

Try adding `id` to your index class and put it in the `fields` list on your serializer. Next, you have added `text` to `ignore_fields` which effectively removes it from the serialized results. 
As for the pagination issue, I'm not quite sure what's going on. Have you set up a global pagination class in your `settings.py` file?

Additionally, if you don't like the default serialized output from DRF's paginators, you'll have to [roll your own](http://www.django-rest-framework.org/api-guide/pagination/#custom-pagination-styles).

**Comment by geekashu** [comment]
I have setup pagination as ...
```
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}
```

I am using django 1.9.6. I think this version is still not supported by haystack. Thus is the pagination issue.

**Comment by rhblind** [comment]
Yup, Haystack only supports django 1.8 at The moment...
