### ISSUE TITLE
HaystackFacetSerializer assumes you use the default pagination class

### ISSUE THREAD

**Issue by hvdklauw** [inonit/drf-haystack#55]
The code assumes you are using the [PageNumberPagination](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/pagination.py#L161) because it tries to get the [page_query_param](https://github.com/inonit/drf-haystack/blob/master/drf_haystack/serializers.py#L345)

We however have the paginator changed to use [LimitOffsetPagination](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/pagination.py#L284)
Which uses the [limit_query_param and offset_queryparam](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/pagination.py#L292)

The same would go if you use another paginator.

A generic solution is not possible I think, but maybe extracting the code that reads the page_query_param into a method would allow me to override that one method to fix it for us without the need to copy the whole _get_narrow_url_ method.

**Comment by rhblind** [comment]
Thanks for the report, I'll take a look at it!

**Comment by hvdklauw** [comment]
Ah, just noticed the _get_narrow_url_ is on the nested class _FacetFieldSerializer_

That might make it a bit harder..

**Comment by rhblind** [comment]
Since we have access to the paginator class, we can query it for its page query parameter name. Next we can use this instead when building the paginated results. Should be a quick fix I think...

**Comment by rhblind** [comment]
Hmm,
The removal of [PAGINATE_BY_PARAMS](http://www.django-rest-framework.org/api-guide/settings/#paginate_by_param) complicates things a little bit.. Needs to figure out something here.

**Comment by hvdklauw** [comment]
For me moving the nested classes to the main level would solve 90% of the
problem, because then I can just  override as needed. Moving the pagination
filtering to it's own class method would solve another 9%. The last percent
I can fix then without much trouble or risk of having to redo it with
upgrades.

**Comment by rhblind** [comment]
Yeah, I guess there's no good reason to keep these private for the `HaystackFacetSerializer`.
I'll take them out, to ease customisability.

I'll also add a hook to specify your own `paginate_by_param`.

**Comment by rhblind** [comment]
Alright, I've extracted the internal fields and serializers on the `HaystackFacetSerializer`, and added some defaults to deal with the three builtin pagination classes; `PageNumberPagination`, `LimitOffsetPagination` and `CursorPagination`.

It seems to work good, but I've yet to write proper tests, so consider it experimental for now.
It's in the master branch, so feel free to check it out.
