### ISSUE TITLE
Use a a complete URL for narrow_url

### ISSUE THREAD

**Issue by clintonb** [inonit/drf-haystack#56]
The `narrow_url` value is actually a path and query string. Update the facet serializer to return a complete URL so that clients don't have to create the URL.

**Comment by rhblind** [comment]
Yes, I know =/
Unfortunately DRF generates the full URI based on the view name, which we don't have access to in the serializer.
We could probably pick the schema, domain and port from the request object.
I'll have another look at it.

**Comment by clintonb** [comment]
See https://docs.djangoproject.com/en/1.8/ref/request-response/#django.http.HttpRequest.build_absolute_uri. Time permitting, I'll post a PR with this change.

**Comment by rhblind** [comment]
Great, thanks!
