### ISSUE TITLE
MultiValueField results serialized as string instead of array

### ISSUE THREAD

**Issue by clintonb** [inonit/drf-haystack#59]
Given the index and serializer below, I would expect the `transcript_languages` field to be rendered as a JSON array (of strings, in this case). However, an array string (e.g. `"['Afrikaans', 'Arabic – United Arab Emirates', 'Arabic – Bahrain']"`) is returned.

The serializer should be updated to render `MultiValueField` data as a JSON array.

```python
class CourseRunIndex(indexes.SearchIndex, indexes.Indexable):
    transcript_languages = indexes.MultiValueField(faceted=True)

    def prepare_transcript_languages(self, obj):
        # language.name is a string
        return [language.name for language in obj.transcript_languages.all()]
```

```python
class CourseRunSearchSerializer(HaystackSerializer):
    class Meta:
        index_classes = [CourseRunIndex]
        fields = ('transcript_languages', 'text',)
        field_aliases = {
            'q': 'text',
        }
        ignore_fields = ('text',)
```

Actual output
```JSON
{
    "dates": {},
    "fields": {
        "transcript_languages": [
            {
                "text": "Arabic – United Arab Emirates",
                "count": 1,
                "narrow_url": "/api/v1/search/course_runs/facets/?selected_facets=transcript_languages_exact%3AArabic+%E2%80%93+United+Arab+Emirates&q=afrikaans"
            },
            {
                "text": "Arabic – Bahrain",
                "count": 1,
                "narrow_url": "/api/v1/search/course_runs/facets/?selected_facets=transcript_languages_exact%3AArabic+%E2%80%93+Bahrain&q=afrikaans"
            },
            {
                "text": "Afrikaans",
                "count": 1,
                "narrow_url": "/api/v1/search/course_runs/facets/?selected_facets=transcript_languages_exact%3AAfrikaans&q=afrikaans"
            }
        ]
    },
    "queries": {},
    "objects": {
        "count": 1,
        "next": null,
        "previous": null,
        "results": [
            {
                "transcript_languages": "['Afrikaans', 'Arabic – United Arab Emirates', 'Arabic – Bahrain']"
            }
        ]
    }
}
```

**Comment by clintonb** [comment]
I resolved this by adding the following to my serializer: `transcript_languages = serializers.ListField(child=serializers.CharField())`.

It would be ideal if `drf-haystack` did this automatically.

**Comment by rhblind** [comment]
Turned out to be a pretty quick fix!

**Comment by clintonb** [comment]
@rhblind Nice! Does the mapping for `FacetMultiValueField` also need to be updated?

**Comment by rhblind** [comment]
I don't think so, it seems like the `MultiValueField` checks itself for faceting properties and returns a `FacetMultiValueField` if existent.

https://github.com/django-haystack/django-haystack/blob/master/haystack/fields.py#L394-L417

**Comment by clintonb** [comment]
Got it. Thanks, again.

**Comment by clintonb** [comment]
@rhblind any plans for a new release soon?

**Comment by rhblind** [comment]
Let me know if you run into issues, I might as well add it for good measures...

Yup, I'll doing the final works for v1.6.0rc1 these days..
I'm kind of holding back waiting for django-haystack 1.5.0 release, but it seems to take forever.
The `1.6.0rc1` will require a minimum of django-haystack `v1.5.dev1`, I'll release the final `1.6.0` when haystack releases `1.5.0`...

**Comment by rhblind** [comment]
@clintonb Just released `v1.6.0rc1`. Still waiting for the `django-haystack` release...

**Comment by clintonb** [comment]
Thanks!

**Comment by rhblind** [comment]
Make sure to check out the [Changelog](http://drf-haystack.readthedocs.io/en/latest/index.html#changelog). Got a few (possibly) breaking changes if you have a lot of custom stuff..
