### ISSUE TITLE
Faceting issue

### ISSUE THREAD

**Issue by hubert10** [inonit/drf-haystack#60]
Hi, thanks for releasing your library. However, I have been having problem with faceting for some days now. I have followed all your steps and also different version combination of drf haystack and elasticsearch, but I don't get any result for facet and no error. So to be sure it is not my code,I tried it with your mockapp and this is what I get when I search http://localhost:8000/search1/?firstname=john/ .

{
    "count": 3,
    "next": null,
    "previous": null,
    "results": [
        {
            "firstname": "John",
            "birthdate": "1952-07-26",
            "text": "John McLaughlin\n",
            "lastname": "McLaughlin",
            "full_name": "John McLaughlin",
            "letters": [
                "J",
                "o",
                "h",
                "n"
            ]
        },
        {
            "firstname": "John",
            "birthdate": "1986-08-05",
            "text": "John McClane\n",
            "lastname": "McClane",
            "full_name": "John McClane",
            "letters": [
                "J",
                "o",
                "h",
                "n"
            ]
        },
        {
            "firstname": "John",
            "birthdate": "1963-12-18",
            "text": "John Baker\n",
            "lastname": "Baker",
            "full_name": "John Baker",
            "letters": [
                "J",

I am guessing it might be elasticsearch version.  These is what I currently have in my virtual environment after different trials.
Django==1.8
django-filter==0.13.0
django-haystack==2.4.0
django-markdown==0.8.4
djangorestframework==3.3.3
drf-haystack==1.5.6
elasticsearch==1.7.0

And local system elasticsearch version is 2.3. And I understand facet has been deprecated starting from elasticsearch v.1, does it mean I have to install ES v 0.90? 

Please, I would appreciate your help on this. Thanks.

**Comment by rhblind** [comment]
Hi,
Yes, you'd have to install the latest 1.x branch of elasticsearch.
Also, you must append `/factes` to the end of your path. Faceting is implemented as an `list action route` on your search view. As from `drf-haystack-1.6.x` branch, you'd also have to include the `FacetMixin` class on your view, but it seems like you are running 1.5.6 so you should be good.

**Comment by hubert10** [comment]
Thanks for your quick response, now I am using ES 1.7 version, still cant get facet to work. Below are my codes, maybe I am not doing something right.

**search index**

class PersonIndex(indexes.SearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)
    firstname = indexes.EdgeNgramField(model_attr='firstname')
    lastname = indexes.CharField(model_attr='lastname', faceted=True)
    fullname = indexes.CharField(model_attr='fullname', faceted=True)
    created = indexes.FacetDateTimeField(model_attr="created")

**Serializers**

class PersonSerializer(serializers.ModelSerializer):
    class Meta:
        model = Person
        fields = '__all__'



class PersonFacetSerializer(HaystackFacetSerializer):

    serialize_objects = True

    class Meta:
        index_classes = [PersonIndex]
        fields = ["firstname", "lastname", "created"]
        field_options = {
            "firstname": {},
            "lastname": {},
            "created": {
                "start_date": datetime.datetime.now() - timedelta(days=3 * 365),
                "end_date": datetime.datetime.now(),
                "gap_by": "day",
                "gap_amount": 3 }
            }

**views**

class PersonFacetViewSet(FacetMixin, HaystackViewSet):
    index_classes = [PersonIndex]
    serializer_class = PersonSerializer
    filter_backends = [HaystackFilter]
    facet_serializer_class = PersonFacetSerializer
    facet_filter_backends = [HaystackFacetFilter]

class PersonSearchView(HaystackViewSet):
    index_models = [Person]
    serializer_class = PersonSerializer
    filter_backends = [HaystackFilter]
    facet_serializer_class = PersonFacetSerializer
    facet_filter_backends = [HaystackFilter]
  

**urls.py**
routerv1.register("person/facets", viewset=PersonSearchView, base_name="person-search")

urlpatterns = [
    url(r'^', include(routerv1.urls)),
    url(r'^facets', include(routerv1.urls)),
    url(r'^', include('backend.urls')),
    url(r'^search', include('haystack.urls')),
    url(r"api/v1/", include(routerv1.urls)),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),

**search result**
GET /api/v1/person/facets/?lastname=adedoyin
{
    "count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
            "firstname": "James",
            "lastname": "Adedoyin",
            "text": "James\nAdedoyin J.O\nAdedoyin\n\n",
            "highlighted": "...<em class=\"highlighted\">Adedoyin</em> J.O\n<em class=\"highlighted\">Adedoyin</em>\n\n"
        },
        {
            "firstname": "James1",
            "lastname": "Adedoyin",
            "text": "James1\nja\nAdedoyin\n\n",
            "highlighted": "...<em class=\"highlighted\">Adedoyin</em>\n\n"
        }
    ]
}

Thank you again.

**Comment by rhblind** [comment]
Try to register the View as
`routerv1.register("person", viewset=PersonSearchView, base_name="person-search")` (notice the removal of `facets` here).

and use this PATH:
`/api/v1/person/facets/`

**Comment by hubert10** [comment]
This is the new result after trying that.
{
    "objects": [
        {
            "lastname": "Adedoyin",
            "firstname": "James",
            "text": "James\nAdedoyin J.O\nAdedoyin\n\n",
            "highlighted": "...<em class=\"highlighted\">Adedoyin</em> J.O\n<em class=\"highlighted\">Adedoyin</em>\n\n"
        },
        {
            "lastname": "Adedoyin",
            "firstname": "James1",
            "text": "James1\nja\nAdedoyin\n\n",
            "highlighted": "...<em class=\"highlighted\">Adedoyin</em>\n\n"
        }
    ]
}

The only change I noticed is the object at the top.

**Comment by hubert10** [comment]
Thanks a bunch, now I can see my facet result. However I noticed when I register as above I'm not able to post new entries but I can see the facet result. I am only able to post when I add /search to it, i.e 
`routerv1.register("person/search", viewset=PersonSearchView, base_name="person-search")`

I don't know if this is normal.

**Comment by rhblind** [comment]
Hm, that's weird. You shouldn't be able to POST new entries at all. The [HaystackViewSet](https://github.com/inonit/drf-haystack/blob/master/drf_haystack/viewsets.py#L11) only implements the `RetrieveModelMixn` and the `ListModelMixin`. After all, it's a REST interface for a search index, so you wouldn't want to POST new data to these endpoints anyway.
