### ISSUE TITLE
1.6.0rc2 broken

### ISSUE THREAD

**Issue by clintonb** [inonit/drf-haystack#61]
Commit https://github.com/inonit/drf-haystack/commit/257cfaaf0a62ed89ac88e5ddf03237ea6055e3c7 includes a breaking change. `get_facet_objects_serializer` expects its `kwargs` dict to include an entry with the key `"object"`; however, the call from `HaystackFacetSerializer.get_objects()` does not include such a value.

**Comment by rhblind** [comment]
Holt cow, thanks for reporting! I'll fix it asap!

**Comment by rhblind** [comment]
Pushed v1.6.0rc3 to pypi
