### ISSUE TITLE
haystack viewset is returning empty results with limit and offset pagination

### ISSUE THREAD

**Issue by karimamer** [inonit/drf-haystack#63]
i have this view
```
class AppSearchView(HaystackViewSet, ProtectedResourceView):
    pagination_class = LimitOffsetPagination
    serializer_class = AppindexSerializer
    max_limit = 50
    index_models = [App]
```
and i am querying using this url but the result is always empty  but if i remove offset and limit from the url i get the results  
`127.0.0.1:8001/v1/App/search/?offset=&limit=20`

```
{
  "count": 0,
  "next": null,
  "previous": null,
  "results": []
}
```

**Comment by rhblind** [comment]
Are you using the latest `v1.6.0rc3` version?

**Comment by rhblind** [comment]
I'm unable to reproduce this, can you try to remove the `ProtectedResourceView` and try again?

**Comment by karimamer** [comment]
@rhblind I removed ProtectedResourceView and upgraded and it worked thanks
