### ISSUE TITLE
Request with an empty string passed as a parameter will cause an Exception - v1.6.0rc3

### ISSUE THREAD

**Issue by SmileyJames** [inonit/drf-haystack#68]
https://github.com/inonit/drf-haystack/blob/62bedeb5df13e01506a883a5f04f543a05da315e/drf_haystack/query.py#L132

If reduce receives an empty list, the following exception is thrown.
```
TypeError reduce() of empty sequence with no initial value
```

The following value for the `filters` variable will trigger the exception.
```
<QueryDict: {'text': ['']}>
```

**Comment by SmileyJames** [comment]
#69 Proposed solution PR

**Comment by rhblind** [comment]
Thank you for reporting!
I'll have a look at the PR later today.

**Comment by rhblind** [comment]
Fixed by merging the PR
