### ISSUE TITLE
Inaccurate Search Result

### ISSUE THREAD

**Issue by alaminopu** [inonit/drf-haystack#70]
Autocomplete Search Result is not accurate when searching with full text.  If I search for "Fayez", it shouldn't show other result. But its okay when I start typing two letter like "Fa". 

![drf-haystack](https://cloud.githubusercontent.com/assets/1296554/16987371/9f319ace-4ead-11e6-9c9c-9eab023f35d6.png)

How can I fix this issue?

**Comment by rhblind** [comment]
Hi,
This has probably to do with the Haystack backend you're using. If using Elasticsearch (don't know if you are), I usually write my own custom engine which overwrites the [DEFAULT_SETTINGS](https://github.com/django-haystack/django-haystack/blob/master/haystack/backends/elasticsearch_backend.py#L58-L100) in order to make "autocomplete" act a bit more naturally...

**Comment by alaminopu** [comment]
Yes, I am using Elasticsearch as Haystack Backend.   Can you give me any hints about overwriting default settings and  achieve the functionality I described above?

**Comment by rhblind** [comment]
Yup, but you'll have to wait a bit...
I'm currently a bit busy at work =)

**Comment by alaminopu** [comment]
Sure, I will wait.

**Comment by rhblind** [comment]
Alright,

I just packaged up what I've been using to do autocomplete search with elasticsearch that "feels" a bit more like you'd expect autocomplete to behave.

Check out [django-hesab](https://github.com/rhblind/django-hesab) (Django-Haystack-Autocomplete-Backend™)

**Comment by alaminopu** [comment]
@rhblind  Thank you for your time to making this package.  I will try it and let you know.  Seems like doc should need to update.

**Comment by rhblind** [comment]
No problem, been thinking about it for a while since I always do this whenever I need to use haystack. Just as good to have it in a package =)

Let me know how if it works, so I can close the issue.

About the docs, I'm not so sure. The code kind of does what it should...

**Comment by alaminopu** [comment]
I have tested the package.  It is working now for exact match, but not working for partial match. I didn't modify the ES_BACKEND_SETTINGS. Look like default should work fine.  Here is my Indexing source code. 

```python
class ProjectIndex(indexes.SearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)
    id = indexes.CharField(model_attr="pk")
    title = indexes.CharField(model_attr="title")
    autocomplete = AutocompleteEdgeNgramField()

    @staticmethod
    def prepare_autocomplete(obj):
        seq = (u"{}".format(obj.title),)
        return ''.join(seq)

    def get_model(self):
        return Project

    def index_queryset(self, using=None):
        return self.get_model().objects.all()
```

So when I start typing "Java", Its not showing result for "Ja" or "Jav". Only return result for "Java".

**Comment by rhblind** [comment]
As far as I can tell the `AutocompleteEdgeNgramField` and backend does what it should. I added some [test cases](https://github.com/rhblind/django-hesab/blob/master/tests/test_query.py) which you can inspect if you'd like to..
If you still think there is any problems with the `hesab` backend, please open a ticket in the `django-hesab` repo.

Other than that I'm not quite sure what's going on... Does it work like expected in the python shell?

```
> results = SearchQureySet().autocomplete(autocomplete='jav')
```

**Comment by alaminopu** [comment]
I figured out the issue.  I was using elasticsearch 2.3.1 which causing the issue.  After removing 2.3.1 and installing 1.7.5 fixed the issue. Thanks again.  You have been a great help.  :D 

You can close the ticket now.

**Comment by rhblind** [comment]
Great!
Yeah, we're currently only supporting the 1.x branch. Need to wait for `django-haystack` to support v2.x, and then I'll have to do some  work to support it as well =/

Glad I could help!
