### ISSUE TITLE
Showing unexpected output

### ISSUE THREAD

**Issue by ashraful-robin** [inonit/drf-haystack#74]
Autocomplete search result is not accurate. I am searching with name and symbol. When I typed "Eric B" or "Eric" then, it's showing result like the image. But I want that "Eric..." related words will show first. And I am trying to search by two fields of one model.(Ex: name or country)

I am using drf-haystack with django-hesab default configuration. And using elasticsearch 1.7.5
![issue-for-hesab](https://cloud.githubusercontent.com/assets/11586533/17937449/f0ce4dbc-6a43-11e6-9390-528eca7d0b38.png)

How can I fix this issue ?

**Comment by rhblind** [comment]
Hi, I'm not really sure...

What does your SearchIndex look like?

Does the query work as expected in the python shell?
My guess is that either you need to tweak your search index, or you'll have to read up on Elasticsearch docs and tweak your settings for the `django-hesab` backend.

**Comment by ashraful-robin** [comment]
On my search index I have name, symbol, id, text, and autocomplete. 
autocomplete = AutocompleteEdgeNgramField()
that is from hesab. 

On the settings file I have declared as doc of hesab.

**Comment by ashraful-robin** [comment]
I have fixed this issue. Basically it was not a bug. it's a feature I think. Here I have name and symbol. Both have same name. And when trying to search then it got higher priority to get search. So that it was showing me the unexpected output first. Thanks for your suggestion @rhblind .

I think you can close the issue @rhblind  :smile:

**Comment by rhblind** [comment]
Alright, great stuff!
