### ISSUE TITLE
format=json on GET breaks an aggregated serializer.

### ISSUE THREAD

**Issue by richardjprice** [inonit/drf-haystack#75]
My current environment is: 
Django 1.9.8, 
Haystack 2.5.0, 
DRF 3.3.3
DRF-Haystack 1.5.6 

My aggregated serializer looks like :

```
class CompanyEntitiesSerializer(HaystackSerializer):
    class Meta:
        index_classes = [CompanyGroupIndex, UserIndex]
        ignore_fields = ['text', ]

```

If I queried this endpoint such as :

/api/v1/companies/entities/?content=Neil

I get the expected results. If however, I had appended 'format=json' to the GET url, I get an empty result set.

I hope that's enough information?

**Comment by rhblind** [comment]
Can you try to upgrade to the latest release and see if that fixes your problem?

**Comment by richardjprice** [comment]
I tried out 1.6.0rc3  before posting the issue too actually and had the same result.

**Comment by rhblind** [comment]
Alright, thanks.
I'll have a look at it, but don't think I have time until next week.

**Comment by richardjprice** [comment]
Thanks, I've found a way around it for my particular scenario, I force a default 'accept' : 'application/json' header to all my json requests instead of passing in a 'format=json' in GET params.

**Comment by rhblind** [comment]
Good.
That's the way I usually does it, so I guess why this hasn't been catched before..
