### ISSUE TITLE
HaystackGenericAPIView.get_object generates two queries

### ISSUE THREAD

**Issue by chriseldredge** [inonit/drf-haystack#76]
The code in [generics.py:89](https://github.com/inonit/drf-haystack/blob/master/drf_haystack/generics.py#L89) issues a query to the backend to fetch the count of documents that match the query, but this does not retrieve or cache the actual list of documents, so when line 90 executes, a second query is issued to the backend.

This means two round trips to the backend with almost identical queries.

The bug may be in Haystack itself, but reducing this code path to a single request would improve performance.

**Comment by rhblind** [comment]
Hello,
Sorry for the delay! Thanks for reporting, I'll have a look into it =)
