### ISSUE TITLE
Django 1.10 _meta.get_all_field_names() removed

### ISSUE THREAD

**Issue by awolfmann** [inonit/drf-haystack#79]
Hello, i'm getting an AttributeError from the HaystackSerializer, with Django 1.10, since the method _meta.get_all_field_names() is deprecated as it says here: [https://docs.djangoproject.com/es/1.10/ref/models/meta/#migrating-from-the-old-api](url)

any update on this?

**Comment by danialgood** [comment]
There are substitute in here https://docs.djangoproject.com/en/1.10/ref/models/meta/#django.db.models.options.Options 

you can create a custom serializer inheriting from the current serializer and override "_get_default_field_kwargs" method and replace model._meta.get_all_field_names() with given choices in the link above.

**Comment by rhblind** [comment]
Thanks for reporting!

**Comment by decibyte** [comment]
This was already fixed months ago. It's even available in `drf-haystack-1.6.0rc3` which seems to  be the only official version on PyPI atm.

**Comment by rhblind** [comment]
Hello,
DRF-Haystack is currently receiving a little more love than it should. I'm very busy with work these days, so unfortunately I don't have enough time to work on this project atm.
Pull requests for issues are deeply appreciated =)
