### ISSUE TITLE
Alternative usage of the search view

### ISSUE THREAD

**Issue by jrief** [inonit/drf-haystack#8]
Often, I don't need a REST ViewSet and the associated routing. Then I prefer normal REST views. 

Currently I use an implementation similar to this one:
```
from rest_framework.mixins import ListModelMixin
from drf_haystack.generics import HaystackGenericAPIView


class SearchView(ListModelMixin, HaystackGenericAPIView):
    """
    A generic view to be used for rendering the result list while searching.
    """
    serializer_class = LocationSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)
```

in urls.py:
```
urlpatterns = (
   ...
    url(r'^search/', SearchView.as_view()),
   ...
)
```

This maybe could be added to the docs, in case others have similar needs.

**Comment by rhblind** [comment]
Great point!
Such use cases should absolutely be in the docs. Thanks.
I've written the docs mostly from my own perspective, so I greatly appreciate inputs like these!
