### ISSUE TITLE
How to serialize nested model?

### ISSUE THREAD

**Issue by awolfmann** [inonit/drf-haystack#80]
I'm trying to do something like this: [http://www.django-rest-framework.org/api-guide/relations/#nested-relationships](url) but i couldn't show the nested data, i'm expecting to get a list of the nested models serialized, but i'm getting null on that field,may be the problem is related to haystack.
i also have looked at this: [http://stackoverflow.com/questions/15351499/using-sqs-with-related-data-haystack](url).
Actually i have defined:
the serializer:
`class ParentSerializer(HaystackSerializer):
    childs = ChildSerializer(many=True, read_only=True)
    class Meta:
        index_classes = [ParentIndex]`

searchindex:
`class ParentIndex(indexes.SearchIndex, indexes.Indexable):
    ....
    childs = indexes.MultiValueField()

```
   def prepare_childs(self,object):
      # just to try with one field
       return [child.field1 for child in object.childs.all()]
```

`
And in the data template
`....
        {% for child in object.childs.all %}
            {{ child.field1 }}
            {{ child.field2 }}
        {% endfor %}
`

How could i solve this?

**Comment by rhblind** [comment]
Hm, does it work from the python shell?

**Comment by awolfmann** [comment]
Nope, but if i use the ModelSerializer from django REST, yes..

**Comment by rhblind** [comment]
Is this still relevant?

**Comment by rhblind** [comment]
Closing due to no answer
