### ISSUE TITLE
Facet Integer Range Field Support

### ISSUE THREAD

**Issue by Tjajeer** [inonit/drf-haystack#82]
Like you have supported the dateRange Field , can you add integer range field to support range values.This will help us in to do facet search on range values like price range in e-commerce websites

**Comment by rhblind** [comment]
Hello,
The support for faceting on date range builds on existing functionality in [django-haystack](https://github.com/django-haystack/django-haystack). As far as I know, doing facet search on a range of numerical values is not supported by haystack itself so I really can't add support for that until haystack supports it.

Sorry, I'd like that functionality myself =/
