### ISSUE TITLE
Including model fields in HaystackSerializer

### ISSUE THREAD

**Issue by vladimirnani** [inonit/drf-haystack#87]
Hey.

I want to include several fields from `CompanyModel` just for display purposes in `HaystackViewSet` but it seems that they must be included in Search Index, even if they are not 'searchable' otherwise they are not returned by serializer.
Am i doing something wrong?

```
class CompanySerializer(HaystackSerializer):
 
    class Meta:
        index_classes = [CompanyIndex]
        model = Company
        fields = ['id', 'name', 'directors', 'registered', 'address']
        search_fields = ['text']
```

```
class CompanyIndex(indexes.SearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)
```
Thanks

**Comment by rhblind** [comment]
Hey,
Yeah, the `HaystackSerializer` does not work with regular models, they need to be included in the search index.
If you'd like to include some fields from your model, I'd just override the `to_representation()` method and add the fields you're interested in.
Or you could look into [reusing model serializers](http://drf-haystack.readthedocs.io/en/latest/10_tips_n_tricks.html#reusing-model-serializers) from the tips'n tricks section to see if that suits your need.

**Comment by rhblind** [comment]
I'm closing this due to no response.
Please reopen if still having issues.
