### ISSUE TITLE
AttributeError when using HaystackSerializerMixin with a ModelSerializer with only 'exclude' specified

### ISSUE THREAD

**Issue by lavoiedn** [inonit/drf-haystack#89]
Trying to use a class that extends drf's ModelSerializer with HaystackSerializerMixin caused issues
when some fields on the meta class were omitted.

Here is a minimal example of the issue:

```python
from drf_haystack.serializers import HaystackSerializerMixin
from drf_haystack.viewsets import HaystackViewSet
from rest_framework.serializers import ModelSerializer

class ProjectSerializer(ModelSerializer):
  class Meta:
    model = Project
    exclude = ('last_edit_timestamp', )
    read_only_fields = ('status', 'slug', )


class ProjectSearchSerializer(HaystackSerializerMixin, ProjectSerializer):
  class Meta(ProjectSerializer.Meta):
      field_aliases = {
          'dateCreated': 'date_created',
      }
      search_fields = ('text', 'status', 'category', 'location', 'author', 'date_created', )


class ProjectSearchViewSet(HaystackViewSet):
    index_models = [Project]
    serializer_class = ProjectSearchSerializer
```

When calling the HaystackViewSet with filters specified in the query parameters, the following error
would occur:
```
Traceback (most recent call last):
File "/home/dlab/git/project/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
  response = self.process_exception_by_middleware(e, request)
File "/home/dlab/git/project/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib64/python3.5/contextlib.py", line 30, in inner
  return func(*args, **kwds)
File "/home/dlab/git/project/env/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
  return view_func(*args, **kwargs)
File "/home/dlab/git/project/env/lib/python3.5/site-packages/rest_framework/viewsets.py", line 83, in view
  return self.dispatch(request, *args, **kwargs)
File "/home/dlab/git/project/env/lib/python3.5/site-packages/rest_framework/views.py", line 477, in dispatch
  response = self.handle_exception(exc)
File "/home/dlab/git/project/env/lib/python3.5/site-packages/rest_framework/views.py", line 437, in handle_exception
  self.raise_uncaught_exception(exc)
File "/home/dlab/git/project/env/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
  response = handler(request, *args, **kwargs)
File "/home/dlab/git/project/env/lib/python3.5/site-packages/rest_framework/mixins.py", line 40, in list
  queryset = self.filter_queryset(self.get_queryset())
File "/home/dlab/git/project/env/lib/python3.5/site-packages/drf_haystack/generics.py", line 98, in filter_queryset
  queryset = super(HaystackGenericAPIView, self).filter_queryset(queryset)
File "/home/dlab/git/project/env/lib/python3.5/site-packages/rest_framework/generics.py", line 151, in filter_queryset
  queryset = backend().filter_queryset(self.request, queryset, self)
File "/home/dlab/git/project/env/lib/python3.5/site-packages/drf_haystack/filters.py", line 58, in filter_queryset
  applicable_filters, applicable_exclusions = self.build_filters(view, filters=self.get_request_filters(request))
File "/home/dlab/git/project/env/lib/python3.5/site-packages/drf_haystack/filters.py", line 45, in build_filters
  return query_builder.build_query(**(filters if filters else {}))
File "/home/dlab/git/project/env/lib/python3.5/site-packages/drf_haystack/query.py", line 121, in build_query
  fields = self.view.serializer_class.Meta.fields
AttributeError: type object 'Meta' has no attribute 'fields'
```
I tried to fix the issue with [this commit](https://github.com/DesjardinsLab/drf-haystack/commit/256a96e4a114cddb9e3cda4e431af1d35ec350c6).

It fixed the issue in my project and the drf-haystack tests ran with no failures locally.

I the fix is judged adequate, I can submit a pull request.

**Comment by rhblind** [comment]
I guess you get the error because it seems like you're not using the `HaystackSerializer` but a `ModelSerializer` which has a slightly different `Meta` class. Usually, the `HaystackSerializer` class is constructed with [this](https://github.com/inonit/drf-haystack/blob/master/drf_haystack/serializers.py#L64) Meta class.

This is really not the intended usage for the `HaystackSerializerMixin` class, so you're likely to encounter more issues down the road. If this is a requested feature case, please feel free to do a proper implementation with tests and submit a PR =)

**Comment by lavoiedn** [comment]
I see!

I was following this example on reusing a ModelSerializer http://drf-haystack.readthedocs.io/en/latest/10_tips_n_tricks.html#drf_haystack.serializers.HaystackSerializerMixin

So I thought that's how the mixin was meant to be used.

**Comment by lavoiedn** [comment]
To add to this issue, [here is a commit](https://github.com/DesjardinsLab/drf-haystack/commit/37c07aabff08a1e1d0f19505ff03081cb54a8f15) with a new test that reproduces the AttributeError on a `HaystackViewSet`. I copied the `HaystackSerializerMixin` and `HaystackViewSet` code from the [serializer tests](https://github.com/inonit/drf-haystack/blob/master/tests/test_serializers.py#L566).

The test `tests.test_viewsets.HaystackViewSetTestCaseWithHaystackSerializerMixin.test_viewset_list_with_query_params` reproduces the AttributeError.

When applying [this fix](https://github.com/inonit/drf-haystack/compare/master...DesjardinsLab:fix-attribute-error) the test passes. It's quite possible this isn't the best way to fix this particular issue, however (if it is even an issue rather than the result of `HaystackSerializerMixin` being used in an unintended way).

**Comment by pymarco** [comment]
Thank you lavoiedn.

I had to define `field_aliases` and `exclude` on my. Here's my working example:

    # contrib
    from drf_haystack.serializers import HaystackSerializerMixin
    from rest_framework import serializers


    # app
    from . import models


    class ProjectSerializer(
        serializers.ModelSerializer,
    ):
        class Meta:
            model = models.Project

            fields = [
                'id',
                'title',
                'url',
            ]


    class SearchSerializer(
        HaystackSerializerMixin,
        ProjectSerializer,
    ):
        class Meta(Project.Meta):
            search_fields = [
                'text',
            ]

            field_aliases = {}
            exclude = tuple()

**Comment by rhblind** [comment]
Guess I can close this one?
