### ISSUE TITLE
drf-haytack filters on multiple models

### ISSUE THREAD

**Issue by hubert10** [inonit/drf-haystack#94]
I have been trying to implement multiple models haystack filters but  it does not work. Here are my examples:
I have two models search_indexes.py

class PersonSkillIndex(indexes.SearchIndex, indexes.Indexable):
   text = indexes.CharField(document=True, use_template=True)
   person_name = indexes.CharField(model_attr='person_id')
   skill_name = indexes.EdgeNgramField(model_attr='skill_id')
   autocomplete = indexes.EdgeNgramField()
   @staticmethod
   def prepare_autocomplete(obj):
       return " ".join((
           obj.skill_id.name))
   def get_model(self):
       return PersonSkill
   def index_queryset(self, using=None):
       return self.get_model().objects.all().select_related('skill_id')
   def prepare_person_id(self, obj):
       return obj.person_id.name
   def prepare_skill_id(self, obj):
       return obj.skill_id.name

class PersonPositionIndex(indexes.SearchIndex, indexes.Indexable):
   text = indexes.CharField(document=True, use_template=True)
   person_name = indexes.CharField(model_attr='person_id')
   position_name = indexes.EdgeNgramField(model_attr='position_id')
   autocomplete = indexes.EdgeNgramField()

   @staticmethod
   def prepare_autocomplete(obj):
       return " ".join(( obj.position_id.title))
   def get_model(self):
       return PersonPosition
   def index_queryset(self, using=None):
       return self.get_model().objects.all()
   def prepare_person_id(self, obj):
       return obj.person_id.name
   def prepare_position_id(self, obj):
       return obj.position_id.name

I want to search on both PersonSkill and PersonPosition models with the following searchQuerySet:
http://localhost:8000/en/api/profiles/search/?skill_name=python&position_name=programmer

Does Haytack filters support this functionality ? if Any suggestions will be welcomed!
Thanks

**Comment by gingerjoos** [comment]
You can index it separately and specify both the models in the `index_models` attribute. Something like this

```
class PersonViewSet(HaystackGenericAPIView):
    index_models = [PersonPosition, PersonSkill]

    def get_queryset(self, *args, **kwargs):
        if self.using is not None:
            qs = SearchQuerySet(using=self.using)
        else:
            qs = SearchQuerySet()
        if len(self.index_models) > 0:
            qs = qs.models(*self.index_models)
        self.queryset = qs
        return self.queryset
```

You will have to write a serializer which can work on both the models

```
class PersonSerializer(HaystackSerializer):
    class Meta:
        index_classes = [PersonPosition, PersonSkill]
        fields = ["name", "field2", "field3"]
````

**Comment by hubert10** [comment]
Thank you for the suggestion! Indeed me I am using a search engine ElasticSearch to index my data to do so with django I used django restframework and Haystack [https://drf-haystack.readthedocs.io/en/latest/01_intro.html](url) to define my search indexes! What I was able to do was to filter on a single model :
 http://localhost:8000/en/api/profiles/search/?skill_name=python&skill_name=mysql

but when it comes on filtering on two or three models it does not bring any results according to the docs it is only it is only possible to create search_index for only one model: [https://django-haystack.readthedocs.io/en/v2.6.0/tutorial.html]()!

Thank you so much

**Comment by rhblind** [comment]
Hi, you'll have to create a separate search index class for each of your models that should be indexed. After that, just add them to a list on your serializer like @gingerjoos suggested above.
