### ISSUE TITLE
[Doubt] There is a way to change the query parameter "from" for a GEO spatial locations filter?

### ISSUE THREAD

**Issue by johnnywell** [inonit/drf-haystack#95]
Hey guys, 

I don't know if there is a discussion group for this project so I'm going to post this here.

I wondering if it's possible to change the query parameter name for a GEO spatial locations filter, I implemented one like the example in the documentation, but I would like to use a serializer to validate the query params and I can't figure out how to do that for a field named from, since it is a keyword in python.

Thanks in advance!

**Comment by rhblind** [comment]
Hi,
Sorry, at the moment the `from` keyword is [hard coded](https://github.com/inonit/drf-haystack/blob/master/drf_haystack/query.py#L279) in the `SpatialQueryBuilder` class.
You can always subclass it and override the `build_query` method.
See https://github.com/inonit/drf-haystack/blob/master/drf_haystack/query.py#L261-L311

```
class MyGeoQueryBuilder(SpatialQueryBuilder):
    def build_query(self, **filters):
        # Custom implementation
        ...

class MyGeoFilter(HaystackGEOSpatialFilter):
    query_builder_class = MyGeoQueryBuilder

class GeoViewSet(HaystackViewSet):
    ...
    filter_backends = [MyGeoFilter]

```

And/or, if feeling generous, you can always submit a PR which implements declaration of the `from` parameter =)
It would of course be better if it's not hard coded.

**Comment by johnnywell** [comment]
I ended up overriding my serializer `_declared_fields` method after declarations, like this.

    QueryParamsSerializer._declared_fields['from'] = QueryParamsSerializer._declared_fields['from_']
    del QueryParamsSerializer._declared_fields['from_']

I'm putting it here in case anybody needs the same for now.

I feeling generous =).

So for the PR, I think the best approach in order to minimize changes in code would be looking for a setting variable like SPATIAL_QUERY_PARAM or something and default it to 'from' to keep compatibility. 

What do you think?
