### ISSUE TITLE
Declared fields returning null value

### ISSUE THREAD

**Issue by SameerRathod** [inonit/drf-haystack#99]
Hello,

```
class AggregateSerializer(HaystackSerializer):
  serialize_objects = True
  extra = serializers.IntegerField()
  _ProductIndex__model_type = serializers.CharField()

 
  class Meta:
    index_classes = [AccountIndex, ProductIndex]
    fields = ["text", "name", "plan", "description"]

  def get_extra(self):
    return 1

  def get__ProductIndex__model_type(self):
    return "Product"

```
I am using the above code for which I am getting declared field as null.Here is the output

 
```results":[{"extra":null,"text":"Mason-Montoya\nTrial","name":"Mason-Montoya","plan":"Trial"}]```

**Comment by rhblind** [comment]
Huh, that's weird.
Looks like a bug :)

**Comment by georgesamy** [comment]
I'm not sure if it's a bug or just a mistake in the docs.. You see, I've had the same issue and using `serializers.SerializerMethodField()` instead of `serializers.CharField()` did the trick for me

**Comment by rhblind** [comment]
@jannon you remember?

**Comment by jannon** [comment]
That does indeed seem like a bug.  I'll see if I can find some time to check it out

**Comment by rhblind** [comment]
Thanks, that would've been awesome!
